language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

install:
  - travis_retry composer install --no-interaction --no-suggest

script:
  - composer test

notifications:
  email: false